### PR TITLE
Fixes bug #150 and #154 related to card rebates and listing card expenditures

### LINKED ISSUE #150: Credit card rebate does not have any cap
Credit card rebate currently does not have any cap, which means user can set it to ridiculous amount. Implement check to ensure rebate does not exceed 0.2 (20%) and update regex from percentage to decimal.
Also to consider changing from decimal (0.2) to percentage (20%).

### LINKED ISSUE #154: Listing of card expenditures does not list paid expenditures
/list /cardexpenditures only list unpaid expenditures. It should also list paid expenditures.

### PR DESCRIPTION
**Pull request by TerenceTanWT**
Resolves #150
Resolves #154

Fixes bug #150 where credit card does not limit to 20% and credit card rebate was incorrectly calculated.
Fixes bug #154 so that when user list card expenditure, paid and unpaid expenditures are listed.

### CODE REVIEW

**Comment by TerenceTanWT** [comment]
Fixes bug #145 /find feature unable to locate card bill and fixes Appveyor JUnit issue.
Resolves #145

Fixes big #145 where the /find feature is unable to locate credit card bill expenditure in savings account when filtering by /date. Also resolves Appveyor JUnit issue by using NEWLINE instead of \n.

**Comment by shamussy** [comment]
There are newline related issues in your junit test code.

**Comment by shamussy** [comment]
image

**Comment by shamussy** [comment]
image

**Comment by TerenceTanWT** [comment]
Thank you for helping me to spot this issue! The test cases works on my IntelliJ and Travis. I am unable to view the exact reason AppVeyor failed my JUnit test cases as I am on a Mac.

**Pull request merged**
